
name: Build and Deploy

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Determine Go version from go.mod
      run: echo "GO_VERSION=$(grep "go 1." go.mod | cut -d " " -f 2)" >> $GITHUB_ENV

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint

    - name: Run build
      run: make build

    - name: Run vet & lint
      run: |
        go vet .
        golint .

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:

    - name: Dispatch Deploy Repo
      uses: peter-evans/repository-dispatch@v1.1.3
      with:
        token: ${{ secrets.DEPLOY_REPO_ACCESS_TOKEN }}
        repository: toksikk/deploy-kaomojiserv
        event-type: deploy
