
name: Build and Deploy

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Determine Go version from go.mod
      run: echo "GO_VERSION=$(grep "go 1." go.mod | cut -d " " -f 2)" >> $GITHUB_ENV

    - name: Setup Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Run build
      run: make build

    - name: Lint
      uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:

    - name: Dispatch Deploy Repo
      uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
      with:
        token: ${{ secrets.DEPLOY_REPO_ACCESS_TOKEN }}
        repository: toksikk/deploy-kaomojiserv
        event-type: deploy
